{
 "title": "App",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "app_horizon_status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_horizon_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "app_horizon_recent_jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_horizon_recent_jobs", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "app_horizon_master_supervisors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_horizon_master_supervisors", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "app_horizon_jobs_per_minute",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 0 },
   "targets": [
    { "expr": "app_horizon_jobs_per_minute", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "app_horizon_failed_jobs_per_hour",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "app_horizon_failed_jobs_per_hour",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "app_my_gauge",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_my_gauge", "legendFormat": "__auto" }
   ]
  }
 ]
}