{
 "title": "Asterisk",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Endpoints Registrados",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (instance, resource)(asterisk_endpoints_state == 2) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Endpoints Registrados por Servidor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count by (instance)(count by (instance, resource)(asterisk_endpoints_state == 2) > 0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Bridges Activos",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(asterisk_bridges_count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Bridges Activos por Servidor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (instance)(asterisk_bridges_count)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}