{
 "title": "Docker Por Instancia",
 "description": "This Grafana dashboard offers a basic overview of key performance metrics for Docker containers in your system.",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Basic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{id=~\".*docker.*[0-9a-f]{12,}.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_replace(sum(rate(container_cpu_usage_seconds_total{id=~\".*docker.*[0-9a-f]{12,}.*\"}[10m])) by (name, id, instance) * 100, \"short_id\", \"$1\", \"id\", \".*(?:docker-|/docker/)([a-f0-9]{12}).*\")",
     "legendFormat": "{{name}} {{short_id}} @ {{instance}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "label_replace(sum(container_memory_usage_bytes{id=~\".*docker.*[0-9a-f]{12,}.*\"}) by (name, id, instance), \"short_id\", \"$1\", \"id\", \".*(?:docker-|/docker/)([a-f0-9]{12}).*\")",
     "legendFormat": "{{name}} {{short_id}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Memory Cached",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "label_replace(sum(container_memory_cache{id=~\".*docker.*[0-9a-f]{12,}.*\"}) by (name, id, instance), \"short_id\", \"$1\", \"id\", \".*(?:docker-|/docker/)([a-f0-9]{12}).*\")",
     "legendFormat": "{{name}} {{short_id}} @ {{instance}}"
    }
   ]
  },
  { "title": "I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Reads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "label_replace(sum(rate(container_fs_reads_bytes_total{id=~\".*docker.*[0-9a-f]{12,}.*\"}[10m])) by (name, id, instance), \"short_id\", \"$1\", \"id\", \".*(?:docker-|/docker/)([a-f0-9]{12}).*\")",
     "legendFormat": "{{name}} {{short_id}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Writes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "label_replace(sum(rate(container_fs_writes_bytes_total{id=~\".*docker.*[0-9a-f]{12,}.*\"}[10m])) by (name, id, instance), \"short_id\", \"$1\", \"id\", \".*(?:docker-|/docker/)([a-f0-9]{12}).*\")",
     "legendFormat": "{{name}} {{short_id}} @ {{instance}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Received Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "label_replace(sum(rate(container_network_receive_bytes_total{id=~\".*docker.*[0-9a-f]{12,}.*\"}[10m])) by (name, id, instance), \"short_id\", \"$1\", \"id\", \".*(?:docker-|/docker/)([a-f0-9]{12}).*\")",
     "legendFormat": "{{name}} {{short_id}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "label_replace(sum(rate(container_network_transmit_bytes_total{id=~\".*docker.*[0-9a-f]{12,}.*\"}[10m])) by (name, id, instance), \"short_id\", \"$1\", \"id\", \".*(?:docker-|/docker/)([a-f0-9]{12}).*\")",
     "legendFormat": "{{name}} {{short_id}} @ {{instance}}"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Container Restarts",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "label_replace(count by(name, instance) (count_over_time(container_last_seen{name=~\".+\"}[$__range])), \"short_id\", \"$1\", \"id\", \".*(?:docker-|/docker/)([a-f0-9]{12}).*\")",
     "legendFormat": "{{name}} {{short_id}} @ {{instance}}"
    }
   ]
  }
 ]
}